### ISSUE TITLE
chrome web store link 404 Error 🔥 

### ISSUE THREAD

**Issue by 2jun0** [volkanakinpasa/what-is-the-different-between#1]
This link is not working!
https://chrome.google.com/webstore/detail/what-is-the-difference-be/obhapnlnfjfbhcbokiemebidfodneopg

![image](https://user-images.githubusercontent.com/7973448/144055409-986b177d-51f7-41c5-977f-19cbf9bc1a3c.png)

please fix the link.

**Comment by volkanakinpasa** [comment]
@2jun0 I can open the link.
